### ISSUE TITLE
bugfix - ModelrelationShipGenerator.php

### ISSUE THREAD

**Issue by Goopil** [19peaches/laravel-generator#1]
your working on an assoc not a numeric array

on method addManyToManyRules (line 155)

change 
$fk1 = $foreign[0];
$fk2 = $foreign[1];

to
$fk1 = array_values($foreign)[0];
$fk2 = array_values($foreign)[1];

**Comment by 19peaches** [comment]
This repo isn't for public consumption, I had no idea people would find it, I'll make it private to prevent this in the future.

Please uninstall and install the original repo:

https://github.com/matmaxanh/laravel-generator

Thanks.

-Vince
