### ISSUE TITLE
PHP Fatal error:  Cannot break/continue 1 level in ...\ModelGenerator.php on line 74

### ISSUE THREAD

**Issue by wouterdialogic** [19peaches/laravel-generator#2]
With laravel 5.2, it installed properly with ("19peaches/laravel-generator": "1.*") you could update that as well.

When running a generate command, i get the following error:

Generating models for: User
PHP Fatal error:  Cannot break/continue 1 level in ...\vendor\19peaches\laravel-generator\src\Generators\ModelGenerator.php on line 74
PHP Stack trace:
PHP   1. {main}() ...\outTrying\artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() ...\outTrying\artisan:36
PHP   3. Symfony\Component\Console\Application->run() ...\outTrying\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:107
PHP   4. Symfony\Component\Console\Application->doRun() ...\outTrying\vendor\symfony\console\Application.php:117
PHP   5. Symfony\Component\Console\Application->doRunCommand() ...\outTrying\vendor\symfony\console\Application.php:186
PHP   6. Illuminate\Console\Command->run() ...\outTrying\vendor\symfony\console\Application.php:787
PHP   7. Symfony\Component\Console\Command\Command->run() ...\outTrying\vendor\laravel\framework\src\Illuminate\Console\Command.php:155
PHP   8. Illuminate\Console\Command->execute() ...\outTrying\vendor\symfony\console\Command\Command.php:256
PHP   9. Illuminate\Container\Container->call() ...\outTrying\vendor\laravel\framework\src\Illuminate\Console\Command.php:169
PHP  10. call_user_func_array:{...\outTrying\vendor\laravel\framework\src\Illuminate\Container\Container.php:507}() ...\outTrying\vendor\laravel\framework\src\Illuminate\Container\Container.php:507
PHP  11. Peaches\Generator\Commands\ModelMakeCommand->handle() ...\outTrying\vendor\laravel\framework\src\Illuminate\Container\Container.php:507
PHP  12. Peaches\Generator\Generators\ModelGenerator->generate() ...\outTrying\vendor\19peaches\laravel-generator\src\Commands\ModelMakeCommand.php:76

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot break/continue 1 level

Thanks

**Comment by 19peaches** [comment]
Hi.

This repo isn't for public consumption, I had no idea people would find it, I'll make it private to prevent this in the future.

Please uninstall and install the original repo:

https://github.com/matmaxanh/laravel-generator

Thanks.

-Vince
