### ISSUE TITLE
Error generating baseRepository.  (filename case mis-match)

### ISSUE THREAD

**Issue by Neopallium** [19peaches/laravel-generator#3]
running:
`php artisan generator:publish --baseRepository`

Fails because of a case mis-match between the code and the template filename.

https://github.com/19peaches/laravel-generator/blob/master/src/Generators/RepositoryGenerator.php#L51

The template name should be: "base/Repository"

**Comment by 19peaches** [comment]
This repo isn't for public use, it's only public for deployment purposes.

**Comment by Neopallium** [comment]
I found it here:
https://packagist.org/packages/19peaches/laravel-generator

Could you please add a note to the README.md file, so other people don't waste time installing it.

**Comment by Neopallium** [comment]
Also you can't replace the Copyright notice, since that is not allowed by the original MIT licence (see lines 12 & 13).  It is ok to add your own Copyright to the license file.
